// フィード初期値（15本）。docs/feeds.opml をもとにした既定ソース一覧。
// siteUrl は OPML の htmlUrl（google のみユーザー確認済みの変更で Chrome for Developers に差し替え）。

import type { Source } from "./types";

export const DEFAULT_SOURCES: Source[] = [
  {
    id: "netflix",
    name: "Netflix TechBlog",
    feedUrl: "https://netflixtechblog.com/feed",
    altFeedUrls: [],
    siteUrl: "https://netflixtechblog.com/",
    initialized: false,
  },
  {
    id: "cloudflare",
    name: "Cloudflare Blog",
    feedUrl: "https://blog.cloudflare.com/rss/",
    altFeedUrls: [],
    siteUrl: "https://blog.cloudflare.com/",
    initialized: false,
  },
  {
    id: "stripe",
    name: "Stripe Blog",
    feedUrl: "https://stripe.com/blog/feed.rss",
    altFeedUrls: [],
    siteUrl: "https://stripe.com/blog/engineering",
    categoryFilter: ["Engineering"],
    initialized: false,
  },
  {
    id: "meta",
    name: "Engineering at Meta",
    feedUrl: "https://engineering.fb.com/feed/",
    altFeedUrls: [],
    siteUrl: "https://engineering.fb.com/",
    initialized: false,
  },
  {
    id: "shopify",
    name: "Shopify Engineering",
    feedUrl: "https://shopify.engineering/blog.atom",
    altFeedUrls: [],
    siteUrl: "https://shopify.engineering/",
    initialized: false,
  },
  {
    id: "uber",
    name: "Uber Engineering",
    feedUrl: "https://www.uber.com/blog/engineering/rss/",
    altFeedUrls: [],
    siteUrl: "https://www.uber.com/us/en/blog/engineering/",
    initialized: false,
  },
  {
    id: "airbnb",
    name: "Airbnb Engineering & Data Science",
    feedUrl: "https://medium.com/feed/airbnb-engineering",
    altFeedUrls: [],
    siteUrl: "https://medium.com/airbnb-engineering",
    initialized: false,
  },
  {
    id: "github",
    name: "GitHub Engineering",
    feedUrl: "https://github.blog/engineering/feed/",
    altFeedUrls: [],
    siteUrl: "https://github.blog/engineering/",
    initialized: false,
  },
  {
    id: "google",
    name: "Chrome for Developers (Google)",
    feedUrl: "https://developer.chrome.com/static/blog/feed.xml",
    altFeedUrls: [
      "https://developers.googleblog.com/feeds/posts/default",
      "https://developers.googleblog.com/feed/",
    ],
    siteUrl: "https://developer.chrome.com/blog",
    initialized: false,
  },
  {
    id: "microsoft",
    name: "Engineering at Microsoft",
    feedUrl: "https://devblogs.microsoft.com/engineering-at-microsoft/feed/",
    altFeedUrls: [],
    siteUrl: "https://devblogs.microsoft.com/engineering-at-microsoft/",
    initialized: false,
  },
  {
    id: "linkedin",
    name: "LinkedIn Engineering",
    feedUrl: "https://engineering.linkedin.com/blog.rss.html",
    altFeedUrls: [
      "https://www.linkedin.com/blog/engineering/rss",
      "https://www.linkedin.com/blog/engineering/feed",
    ],
    siteUrl: "https://www.linkedin.com/blog/engineering",
    initialized: false,
  },
  {
    id: "spotify",
    name: "Spotify Engineering",
    feedUrl: "https://engineering.atspotify.com/feed",
    altFeedUrls: [],
    siteUrl: "https://engineering.atspotify.com/",
    initialized: false,
  },
  {
    id: "pinterest",
    name: "Pinterest Engineering",
    feedUrl: "https://medium.com/feed/pinterest-engineering",
    altFeedUrls: [],
    siteUrl: "https://medium.com/pinterest-engineering",
    initialized: false,
  },
  {
    id: "atlassian",
    name: "Atlassian Engineering",
    feedUrl: "https://www.atlassian.com/blog/atlassian-engineering/feed",
    altFeedUrls: [],
    siteUrl: "https://www.atlassian.com/blog/atlassian-engineering/cloud-overview",
    initialized: false,
  },
  {
    id: "slack",
    name: "Slack Engineering",
    feedUrl: "https://slack.engineering/feed/",
    altFeedUrls: [],
    siteUrl: "https://slack.engineering/",
    initialized: false,
  },
];
